name: timer_bloc
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.1
  equatable: ^2.0.5
  http: ^0.13.6
  sqflite: ^2.0.0
  path: ^1.8.0
  get_it: ^7.2.0
  injectable: ^2.3.2
  visibility_detector: ^0.4.0+2


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: any
  injectable_generator:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  generate: true

  uses-material-design: true

  # assets:
  #   - images/a_dot_ham.jpeg
  #   - images/a_dot_ham.jpeg

